package com.prakash.busi.model;
// default package
// Generated Jun 9, 2017 8:36:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * LBusinesstype generated by hbm2java
 */
@Entity
@Table(name = "l_businesstype", catalog = "business")
public class LBusinesstype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long busitypeid;
	private Integer version;
	private Date createddate;
	private Date lastupdateddate;
	private String description;
	private String busiType;
	private Long createdby;
	private Long updatedby;
	private Set<LCategory> LCategories = new HashSet<LCategory>(0);
	private Set<TBusinesssrc> TBusinesssrcs = new HashSet<TBusinesssrc>(0);

	public LBusinesstype() {
	}

	public LBusinesstype(Date createddate, Date lastupdateddate, String busiType) {
		this.createddate = createddate;
		this.lastupdateddate = lastupdateddate;
		this.busiType = busiType;
	}

	public LBusinesstype(Date createddate, Date lastupdateddate,
			String description, String busiType, Long createdby,
			Long updatedby, Set<LCategory> LCategories,
			Set<TBusinesssrc> TBusinesssrcs) {
		this.createddate = createddate;
		this.lastupdateddate = lastupdateddate;
		this.description = description;
		this.busiType = busiType;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.LCategories = LCategories;
		this.TBusinesssrcs = TBusinesssrcs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "busitypeid", unique = true, nullable = false)
	public Long getBusitypeid() {
		return this.busitypeid;
	}

	public void setBusitypeid(Long busitypeid) {
		this.busitypeid = busitypeid;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createddate", nullable = false, length = 19)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastupdateddate", nullable = false, length = 19)
	public Date getLastupdateddate() {
		return this.lastupdateddate;
	}

	public void setLastupdateddate(Date lastupdateddate) {
		this.lastupdateddate = lastupdateddate;
	}

	@Column(name = "description", length = 800)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "BusiType", nullable = false, length = 200)
	public String getBusiType() {
		return this.busiType;
	}

	public void setBusiType(String busiType) {
		this.busiType = busiType;
	}

	@Column(name = "createdby")
	public Long getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Long createdby) {
		this.createdby = createdby;
	}

	@Column(name = "updatedby")
	public Long getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Long updatedby) {
		this.updatedby = updatedby;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "LBusinesstype")
	public Set<LCategory> getLCategories() {
		return this.LCategories;
	}

	public void setLCategories(Set<LCategory> LCategories) {
		this.LCategories = LCategories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "LBusinesstype")
	public Set<TBusinesssrc> getTBusinesssrcs() {
		return this.TBusinesssrcs;
	}

	public void setTBusinesssrcs(Set<TBusinesssrc> TBusinesssrcs) {
		this.TBusinesssrcs = TBusinesssrcs;
	}

}
