package com.prakash.busi.model;
// default package
// Generated Jun 9, 2017 8:36:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * LCategory generated by hbm2java
 */
@Entity
@Table(name = "l_category", catalog = "business")
public class LCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long categoryid;
	private Integer version;
	private LBusinesstype LBusinesstype;
	private String categoryname;
	private Date createddate;
	private Date lastupdateddate;
	private String description;
	private Long createdby;
	private Long updatedby;
	private Long parentid;

	public LCategory() {
	}

	public LCategory(long categoryid) {
		this.categoryid = categoryid;
	}

	public LCategory(long categoryid, LBusinesstype LBusinesstype,
			String categoryname, Date createddate, Date lastupdateddate,
			String description, Long createdby, Long updatedby, Long parentid) {
		this.categoryid = categoryid;
		this.LBusinesstype = LBusinesstype;
		this.categoryname = categoryname;
		this.createddate = createddate;
		this.lastupdateddate = lastupdateddate;
		this.description = description;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.parentid = parentid;
	}

	@Id
	@Column(name = "categoryid", unique = true, nullable = false)
	public long getCategoryid() {
		return this.categoryid;
	}

	public void setCategoryid(long categoryid) {
		this.categoryid = categoryid;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "busitypeid")
	public LBusinesstype getLBusinesstype() {
		return this.LBusinesstype;
	}

	public void setLBusinesstype(LBusinesstype LBusinesstype) {
		this.LBusinesstype = LBusinesstype;
	}

	@Column(name = "categoryname", length = 50)
	public String getCategoryname() {
		return this.categoryname;
	}

	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createddate", length = 19)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastupdateddate", length = 19)
	public Date getLastupdateddate() {
		return this.lastupdateddate;
	}

	public void setLastupdateddate(Date lastupdateddate) {
		this.lastupdateddate = lastupdateddate;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "createdby")
	public Long getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Long createdby) {
		this.createdby = createdby;
	}

	@Column(name = "updatedby")
	public Long getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Long updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "parentid")
	public Long getParentid() {
		return this.parentid;
	}

	public void setParentid(Long parentid) {
		this.parentid = parentid;
	}

}
