package com.prakash.busi.model;
// default package
// Generated Jun 9, 2017 8:36:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * LCity generated by hbm2java
 */
@Entity
@Table(name = "l_city", catalog = "business")
public class LCity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long cityid;
	private Integer version;
	private LState LState;
	private String cityname;
	private String description;
	private Date createddate;
	private Date lastupdateddate;
	private Long createdby;
	private Long updatedby;
	private long status;
	private Set<LZipcode> LZipcodes = new HashSet<LZipcode>(0);
	private Set<TAddresses> TAddresseses = new HashSet<TAddresses>(0);

	public LCity() {
	}

	public LCity(Date createddate, Date lastupdateddate, long status) {
		this.createddate = createddate;
		this.lastupdateddate = lastupdateddate;
		this.status = status;
	}

	public LCity(LState LState, String cityname, String description,
			Date createddate, Date lastupdateddate, Long createdby,
			Long updatedby, long status, Set<LZipcode> LZipcodes,
			Set<TAddresses> TAddresseses) {
		this.LState = LState;
		this.cityname = cityname;
		this.description = description;
		this.createddate = createddate;
		this.lastupdateddate = lastupdateddate;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.status = status;
		this.LZipcodes = LZipcodes;
		this.TAddresseses = TAddresseses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cityid", unique = true, nullable = false)
	public Long getCityid() {
		return this.cityid;
	}

	public void setCityid(Long cityid) {
		this.cityid = cityid;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stateid")
	public LState getLState() {
		return this.LState;
	}

	public void setLState(LState LState) {
		this.LState = LState;
	}

	@Column(name = "cityname", length = 50)
	public String getCityname() {
		return this.cityname;
	}

	public void setCityname(String cityname) {
		this.cityname = cityname;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createddate", nullable = false, length = 19)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastupdateddate", nullable = false, length = 19)
	public Date getLastupdateddate() {
		return this.lastupdateddate;
	}

	public void setLastupdateddate(Date lastupdateddate) {
		this.lastupdateddate = lastupdateddate;
	}

	@Column(name = "createdby")
	public Long getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Long createdby) {
		this.createdby = createdby;
	}

	@Column(name = "updatedby")
	public Long getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Long updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "status", nullable = false)
	public long getStatus() {
		return this.status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "LCity")
	public Set<LZipcode> getLZipcodes() {
		return this.LZipcodes;
	}

	public void setLZipcodes(Set<LZipcode> LZipcodes) {
		this.LZipcodes = LZipcodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "LCity")
	public Set<TAddresses> getTAddresseses() {
		return this.TAddresseses;
	}

	public void setTAddresseses(Set<TAddresses> TAddresseses) {
		this.TAddresseses = TAddresseses;
	}

}
