package com.prakash.busi.model;
// default package
// Generated Jun 9, 2017 8:36:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * LCountry generated by hbm2java
 */
@Entity
@Table(name = "l_country", catalog = "business")
public class LCountry implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long countryid;
	private Integer version;
	private String countryname;
	private String description;
	private Date createdDate;
	private Date lastUpdatedDate;
	private Long createdBy;
	private Long updatedBy;
	private long status;
	private Long countryCode;
	private Set<LState> LStates = new HashSet<LState>(0);
	private Set<TAddresses> TAddresseses = new HashSet<TAddresses>(0);
	private Set<TBusinesscontact> TBusinesscontacts = new HashSet<TBusinesscontact>(
			0);

	public LCountry() {
	}

	public LCountry(Date createdDate, Date lastUpdatedDate, long status) {
		this.createdDate = createdDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.status = status;
	}

	public LCountry(String countryname, String description, Date createdDate,
			Date lastUpdatedDate, Long createdBy, Long updatedBy, long status,
			Set<LState> LStates, Set<TAddresses> TAddresseses,
			Set<TBusinesscontact> TBusinesscontacts) {
		this.countryname = countryname;
		this.description = description;
		this.createdDate = createdDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.status = status;
		this.LStates = LStates;
		this.TAddresseses = TAddresseses;
		this.TBusinesscontacts = TBusinesscontacts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "countryid", unique = true, nullable = false)
	public Long getCountryid() {
		return this.countryid;
	}

	public void setCountryid(Long countryid) {
		this.countryid = countryid;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "countryname", length = 50)
	public String getCountryname() {
		return this.countryname;
	}

	public void setCountryname(String countryname) {
		this.countryname = countryname;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastUpdatedDate", nullable = false, length = 19)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Column(name = "CreatedBy")
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "UpdatedBy")
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "status", nullable = false)
	public long getStatus() {
		return this.status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "LCountry")
	public Set<LState> getLStates() {
		return this.LStates;
	}

	public void setLStates(Set<LState> LStates) {
		this.LStates = LStates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "LCountry")
	public Set<TAddresses> getTAddresseses() {
		return this.TAddresseses;
	}

	public void setTAddresseses(Set<TAddresses> TAddresseses) {
		this.TAddresseses = TAddresseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "LCountry")
	public Set<TBusinesscontact> getTBusinesscontacts() {
		return this.TBusinesscontacts;
	}

	public void setTBusinesscontacts(Set<TBusinesscontact> TBusinesscontacts) {
		this.TBusinesscontacts = TBusinesscontacts;
	}

	public Long getCountryCode() {
		return countryCode;
	}

	public void setCountryCode(Long countryCode) {
		this.countryCode = countryCode;
	}

	
}
