package com.prakash.busi.model;
// default package
// Generated Jun 9, 2017 8:36:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * LZipcode generated by hbm2java
 */
@Entity
@Table(name = "l_zipcode", catalog = "business")
public class LZipcode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long zipid;
	private Integer version;
	private LCity LCity;
	private Long zipcode;
	private String description;
	private Date createddate;
	private Date lastupdateddate;
	private Long createdby;
	private Long updatedby;
	private long status;
	private Set<LArea> LAreas = new HashSet<LArea>(0);
	private Set<TAddresses> TAddresseses = new HashSet<TAddresses>(0);

	public LZipcode() {
	}

	public LZipcode(String description, Date createddate, Date lastupdateddate) {
		this.description = description;
		this.createddate = createddate;
		this.lastupdateddate = lastupdateddate;
	}

	public LZipcode(LCity LCity, Long zipcode, String description,
			Date createddate, Date lastupdateddate, Long createdby,
			Long updatedby, Set<LArea> LAreas, Set<TAddresses> TAddresseses) {
		this.LCity = LCity;
		this.zipcode = zipcode;
		this.description = description;
		this.createddate = createddate;
		this.lastupdateddate = lastupdateddate;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.LAreas = LAreas;
		this.TAddresseses = TAddresseses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "zipid", unique = true, nullable = false)
	public Long getZipid() {
		return this.zipid;
	}

	public void setZipid(Long zipid) {
		this.zipid = zipid;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cityid")
	public LCity getLCity() {
		return this.LCity;
	}

	public void setLCity(LCity LCity) {
		this.LCity = LCity;
	}

	@Column(name = "zipcode")
	public Long getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(Long zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "description", nullable = false, length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createddate", nullable = false, length = 19)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastupdateddate", nullable = false, length = 19)
	public Date getLastupdateddate() {
		return this.lastupdateddate;
	}

	public void setLastupdateddate(Date lastupdateddate) {
		this.lastupdateddate = lastupdateddate;
	}

	@Column(name = "createdby")
	public Long getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Long createdby) {
		this.createdby = createdby;
	}

	@Column(name = "updatedby")
	public Long getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Long updatedby) {
		this.updatedby = updatedby;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "LZipcode")
	public Set<LArea> getLAreas() {
		return this.LAreas;
	}

	public void setLAreas(Set<LArea> LAreas) {
		this.LAreas = LAreas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "LZipcode")
	public Set<TAddresses> getTAddresseses() {
		return this.TAddresseses;
	}

	public void setTAddresseses(Set<TAddresses> TAddresseses) {
		this.TAddresseses = TAddresseses;
	}

	public long getStatus() {
		return status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

}
