package com.prakash.busi.model;
// default package
// Generated Feb 26, 2017 8:38:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * TAddresses generated by hbm2java
 */
@Entity
@Table(name = "t_addresses", catalog = "business")
public class TAddresses implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long addressId;
	private Integer version;
	private TUser TUser;
	private long countryid;
	private long stateid;
	private long cityid;
	private long zipcode;
	private String landmark;
	private String address;
	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd hh:mm a z",timezone="IST")
	private Date createddate;
	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd hh:mm a z",timezone="IST")
	private Date lastupdateddate;
	private Long createdby;
	private Long updatedby;
	private Long status;

	public TAddresses() {
	}

	public TAddresses(TUser TUser, long countryid, long stateid, long cityid,
			long zipcode, String address, Date createddate, Date lastupdateddate) {
		this.TUser = TUser;
		this.countryid = countryid;
		this.stateid = stateid;
		this.cityid = cityid;
		this.zipcode = zipcode;
		this.address = address;
		this.createddate = createddate;
		this.lastupdateddate = lastupdateddate;
	}

	public TAddresses(TUser TUser, long countryid, long stateid, long cityid,
			long zipcode, String landmark, String address, Date createddate,
			Date lastupdateddate, Long createdby, Long updatedby, Long status) {
		this.TUser = TUser;
		this.countryid = countryid;
		this.stateid = stateid;
		this.cityid = cityid;
		this.zipcode = zipcode;
		this.landmark = landmark;
		this.address = address;
		this.createddate = createddate;
		this.lastupdateddate = lastupdateddate;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AddressID", unique = true, nullable = false)
	public Long getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Long addressId) {
		this.addressId = addressId;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false)
	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	@Column(name = "countryid", nullable = false)
	public long getCountryid() {
		return this.countryid;
	}

	public void setCountryid(long countryid) {
		this.countryid = countryid;
	}

	@Column(name = "stateid", nullable = false)
	public long getStateid() {
		return this.stateid;
	}

	public void setStateid(long stateid) {
		this.stateid = stateid;
	}

	@Column(name = "cityid", nullable = false)
	public long getCityid() {
		return this.cityid;
	}

	public void setCityid(long cityid) {
		this.cityid = cityid;
	}

	@Column(name = "zipcode", nullable = false)
	public long getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(long zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "landmark", length = 200)
	public String getLandmark() {
		return this.landmark;
	}

	public void setLandmark(String landmark) {
		this.landmark = landmark;
	}

	@Column(name = "Address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createddate", nullable = false, length = 19)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastupdateddate", nullable = false, length = 19)
	public Date getLastupdateddate() {
		return this.lastupdateddate;
	}

	public void setLastupdateddate(Date lastupdateddate) {
		this.lastupdateddate = lastupdateddate;
	}

	@Column(name = "createdby")
	public Long getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Long createdby) {
		this.createdby = createdby;
	}

	@Column(name = "updatedby")
	public Long getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Long updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "status")
	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

}
