package com.prakash.busi.model;
// default package
// Generated Jun 9, 2017 8:36:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * TBusinesscontact generated by hbm2java
 */
@Entity
@Table(name = "t_businesscontact", catalog = "business")
public class TBusinesscontact implements java.io.Serializable {

	private Long contactid;
	private Integer version;
	private TBusinesssrc TBusinesssrc;
	private LCountry LCountry;
	private Long phoneNo;
	private long mobileNo1;
	private Long mobileNo2;
	private Long landLineNo;
	private String emailId1;
	private String emailId2;
	private Date createdDate;
	private Date lastUpdateddate;
	private long createdBy;
	private long updatedBy;
	private Long areaCode;
	private String contactPersonFName;
	private String contactPersonMName;
	private String contactPersonLName;

	public TBusinesscontact() {
	}

	public TBusinesscontact(LCountry LCountry, long mobileNo1, String emailId1,
			Date createdDate, Date lastUpdateddate, long createdBy,
			long updatedBy, String contactPersonLName) {
		this.LCountry = LCountry;
		this.mobileNo1 = mobileNo1;
		this.emailId1 = emailId1;
		this.createdDate = createdDate;
		this.lastUpdateddate = lastUpdateddate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.contactPersonLName = contactPersonLName;
	}

	public TBusinesscontact(TBusinesssrc TBusinesssrc, LCountry LCountry,
			Long phoneNo, long mobileNo1, Long mobileNo2, Long landLineNo,
			String emailId1, String emailId2, Date createdDate,
			Date lastUpdateddate, long createdBy, long updatedBy,
			Long areaCode, String contactPersonFName,
			String contactPersonMName, String contactPersonLName) {
		this.TBusinesssrc = TBusinesssrc;
		this.LCountry = LCountry;
		this.phoneNo = phoneNo;
		this.mobileNo1 = mobileNo1;
		this.mobileNo2 = mobileNo2;
		this.landLineNo = landLineNo;
		this.emailId1 = emailId1;
		this.emailId2 = emailId2;
		this.createdDate = createdDate;
		this.lastUpdateddate = lastUpdateddate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.areaCode = areaCode;
		this.contactPersonFName = contactPersonFName;
		this.contactPersonMName = contactPersonMName;
		this.contactPersonLName = contactPersonLName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "contactid", unique = true, nullable = false)
	public Long getContactid() {
		return this.contactid;
	}

	public void setContactid(Long contactid) {
		this.contactid = contactid;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BusiSrcID")
	public TBusinesssrc getTBusinesssrc() {
		return this.TBusinesssrc;
	}

	public void setTBusinesssrc(TBusinesssrc TBusinesssrc) {
		this.TBusinesssrc = TBusinesssrc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CountryCode", nullable = false)
	public LCountry getLCountry() {
		return this.LCountry;
	}

	public void setLCountry(LCountry LCountry) {
		this.LCountry = LCountry;
	}

	@Column(name = "PhoneNo")
	public Long getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(Long phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "MobileNo1", nullable = false)
	public long getMobileNo1() {
		return this.mobileNo1;
	}

	public void setMobileNo1(long mobileNo1) {
		this.mobileNo1 = mobileNo1;
	}

	@Column(name = "MobileNo2")
	public Long getMobileNo2() {
		return this.mobileNo2;
	}

	public void setMobileNo2(Long mobileNo2) {
		this.mobileNo2 = mobileNo2;
	}

	@Column(name = "LandLineNo")
	public Long getLandLineNo() {
		return this.landLineNo;
	}

	public void setLandLineNo(Long landLineNo) {
		this.landLineNo = landLineNo;
	}

	@Column(name = "EmailId1", nullable = false, length = 50)
	public String getEmailId1() {
		return this.emailId1;
	}

	public void setEmailId1(String emailId1) {
		this.emailId1 = emailId1;
	}

	@Column(name = "EmailId2", length = 50)
	public String getEmailId2() {
		return this.emailId2;
	}

	public void setEmailId2(String emailId2) {
		this.emailId2 = emailId2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastUpdateddate", nullable = false, length = 19)
	public Date getLastUpdateddate() {
		return this.lastUpdateddate;
	}

	public void setLastUpdateddate(Date lastUpdateddate) {
		this.lastUpdateddate = lastUpdateddate;
	}

	@Column(name = "CreatedBy", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "UpdatedBy", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "AreaCode")
	public Long getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(Long areaCode) {
		this.areaCode = areaCode;
	}

	@Column(name = "ContactPerson_fName", length = 50)
	public String getContactPersonFName() {
		return this.contactPersonFName;
	}

	public void setContactPersonFName(String contactPersonFName) {
		this.contactPersonFName = contactPersonFName;
	}

	@Column(name = "ContactPerson_mName", length = 50)
	public String getContactPersonMName() {
		return this.contactPersonMName;
	}

	public void setContactPersonMName(String contactPersonMName) {
		this.contactPersonMName = contactPersonMName;
	}

	@Column(name = "ContactPerson_lName", nullable = false, length = 50)
	public String getContactPersonLName() {
		return this.contactPersonLName;
	}

	public void setContactPersonLName(String contactPersonLName) {
		this.contactPersonLName = contactPersonLName;
	}

}
