package com.prakash.busi.model;
// default package
// Generated Feb 26, 2017 8:38:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * TUser generated by hbm2java
 */
@Entity
@Table(name = "t_user", catalog = "business", uniqueConstraints = @UniqueConstraint(columnNames = "email_id"))
public class TUser implements java.io.Serializable {

	private Long id;
	private Integer version;
	private String emailId;
	private String password;
	private Date createdDate;
	private Date lastUpdatedDate;
	private Long createdBy;
	private Long updatedBy;
	private Boolean active;
	private String previousPassword;
	private Boolean locked;
	private Date lastPasswordChangedOn;
	private long roleId;
	private Date dob;
	private Set<TAddresses> TAddresseses = new HashSet<TAddresses>(0);
	private Set<TBusinesssrc> TBusinesssrcs = new HashSet<TBusinesssrc>(0);

	public TUser() {
	}

	public TUser(String emailId, String password, long roleId) {
		this.emailId = emailId;
		this.password = password;
		this.roleId = roleId;
	}

	public TUser(String emailId, String password, Date createdDate,
			Date lastUpdatedDate, Long createdBy, Long updatedBy,
			Boolean active, String previousPassword, Boolean locked,
			Date lastPasswordChangedOn, long roleId, Date dob,
			Set<TAddresses> TAddresseses, Set<TBusinesssrc> TBusinesssrcs) {
		this.emailId = emailId;
		this.password = password;
		this.createdDate = createdDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.active = active;
		this.previousPassword = previousPassword;
		this.locked = locked;
		this.lastPasswordChangedOn = lastPasswordChangedOn;
		this.roleId = roleId;
		this.dob = dob;
		this.TAddresseses = TAddresseses;
		this.TBusinesssrcs = TBusinesssrcs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "email_id", unique = true, nullable = false, length = 50)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_date", length = 19)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Column(name = "created_by")
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by")
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "previous_password", length = 100)
	public String getPreviousPassword() {
		return this.previousPassword;
	}

	public void setPreviousPassword(String previousPassword) {
		this.previousPassword = previousPassword;
	}

	@Column(name = "locked")
	public Boolean getLocked() {
		return this.locked;
	}

	public void setLocked(Boolean locked) {
		this.locked = locked;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_password_changed_on", length = 19)
	public Date getLastPasswordChangedOn() {
		return this.lastPasswordChangedOn;
	}

	public void setLastPasswordChangedOn(Date lastPasswordChangedOn) {
		this.lastPasswordChangedOn = lastPasswordChangedOn;
	}

	@Column(name = "role_id", nullable = false)
	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dob", length = 19)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TUser")
	public Set<TAddresses> getTAddresseses() {
		return this.TAddresseses;
	}

	public void setTAddresseses(Set<TAddresses> TAddresseses) {
		this.TAddresseses = TAddresseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TUser")
	public Set<TBusinesssrc> getTBusinesssrcs() {
		return this.TBusinesssrcs;
	}

	public void setTBusinesssrcs(Set<TBusinesssrc> TBusinesssrcs) {
		this.TBusinesssrcs = TBusinesssrcs;
	}

}
